-- VEPs (Volante Electrónico de Pago) Database Schema
-- Run this in your Supabase SQL Editor

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- VEPs table: stores VEP payment voucher data
CREATE TABLE IF NOT EXISTS veps (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  file_id UUID REFERENCES files(id) ON DELETE CASCADE,

  -- VEP Core Information
  nro_vep TEXT NOT NULL, -- VEP Number (e.g., "1528847816")
  organismo_recaudador TEXT, -- Collection Agency (e.g., "ARCA")
  tipo_pago TEXT, -- Payment Type (e.g., "Empleadores SICOSS - Saldo DJ")
  descripcion_reducida TEXT, -- Short Description (e.g., "SIJPDJ09/25")
  cuit TEXT NOT NULL, -- CUIT (e.g., "30-71600516-6")
  concepto TEXT, -- Concept (e.g., "19 OBLIGACION MENSUAL/ANUAL")
  subconcepto TEXT, -- Sub-concept
  periodo TEXT, -- Period (e.g., "2025-09")

  -- Generation Information
  generado_por_usuario TEXT, -- Generated by User (e.g., "20371787373")
  fecha_generacion DATE, -- Generation Date
  dia_expiracion DATE, -- Expiration Date

  -- Payment Amount
  importe_total_pagar DECIMAL(15,2) NOT NULL, -- Total Amount to Pay

  -- Additional line items (stored as JSONB for flexibility)
  items_detalle JSONB, -- Detailed items breakdown

  -- Processing Metadata
  confidence_score DECIMAL(5,2), -- OCR confidence score
  raw_data JSONB, -- Store original extracted data

  -- Multi-user support (for future)
  user_id UUID, -- Will be populated when auth is added

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_veps_file_id ON veps(file_id);
CREATE INDEX IF NOT EXISTS idx_veps_user_id ON veps(user_id);
CREATE INDEX IF NOT EXISTS idx_veps_nro_vep ON veps(nro_vep);
CREATE INDEX IF NOT EXISTS idx_veps_cuit ON veps(cuit);
CREATE INDEX IF NOT EXISTS idx_veps_fecha_generacion ON veps(fecha_generacion DESC);
CREATE INDEX IF NOT EXISTS idx_veps_dia_expiracion ON veps(dia_expiracion DESC);
CREATE INDEX IF NOT EXISTS idx_veps_created_at ON veps(created_at DESC);

-- Add trigger to auto-update updated_at
DROP TRIGGER IF EXISTS update_veps_updated_at ON veps;
CREATE TRIGGER update_veps_updated_at
  BEFORE UPDATE ON veps
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS) for multi-user support
ALTER TABLE veps ENABLE ROW LEVEL SECURITY;

-- Create policy (allow all for now, will restrict when auth is added)
CREATE POLICY "Allow all operations on veps for now"
  ON veps
  FOR ALL
  TO public
  USING (true)
  WITH CHECK (true);

-- Add a document_type column to files table to distinguish VEPs from bank statements
ALTER TABLE files ADD COLUMN IF NOT EXISTS document_type TEXT DEFAULT 'bank_statement'; -- 'bank_statement' or 'vep'

-- Verify table was created
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
AND table_name = 'veps'
ORDER BY ordinal_position;
